/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActivitiesSliderCard: typeof import('./src/components/homepage/ActivitiesSliderCard.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Cards: typeof import('./src/components/ui/Cards.vue')['default']
    ContactForm: typeof import('./src/components/forms/ContactForm.vue')['default']
    ContactUs: typeof import('./src/components/footer/ContactUs.vue')['default']
    Content: typeof import('./src/components/ui/Content.vue')['default']
    DemoOverviewActivities: typeof import('./src/components/activities/demo/DemoOverviewActivities.vue')['default']
    DemoTable: typeof import('./src/components/demo/DemoTable.vue')['default']
    DynamicTable: typeof import('./src/components/ui/DynamicTable.vue')['default']
    EpaButton: typeof import('./src/components/ui/EpaButton.vue')['default']
    EpaIcon: typeof import('./src/components/ui/EpaIcon.vue')['default']
    Footer: typeof import('./src/components/footer/Footer.vue')['default']
    FooterMenu: typeof import('./src/components/menu/FooterMenu.vue')['default']
    Form: typeof import('@primevue/forms/form')['default']
    GoogleMaps: typeof import('./src/components/footer/GoogleMaps.vue')['default']
    Header: typeof import('./src/components/header/Header.vue')['default']
    HomepageCards: typeof import('./src/components/homepage/HomepageCards.vue')['default']
    HomepageSlider: typeof import('./src/components/homepage/HomepageSlider.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InformationActivites: typeof import('./src/components/activities/InformationActivites.vue')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LanguageSwitcher: typeof import('./src/components/ui/LanguageSwitcher.vue')['default']
    LatestActivities: typeof import('./src/components/activities/LatestActivities.vue')['default']
    LatestNews: typeof import('./src/components/news/LatestNews.vue')['default']
    Logo: typeof import('./src/components/ui/Logo.vue')['default']
    LogoSlider: typeof import('./src/components/logos/LogoSlider.vue')['default']
    MainMenu: typeof import('./src/components/menu/MainMenu.vue')['default']
    MenuInfo: typeof import('./src/components/menu/MenuInfo.vue')['default']
    Message: typeof import('primevue/message')['default']
    OpenMaps: typeof import('./src/components/footer/OpenMaps.vue')['default']
    OverviewActivities: typeof import('./src/components/activities/OverviewActivities.vue')['default']
    OverviewNews: typeof import('./src/components/news/OverviewNews.vue')['default']
    Pagination: typeof import('./src/components/ui/Pagination.vue')['default']
    Paginator: typeof import('./src/components/ui/Paginator.vue')['default']
    PastActivities: typeof import('./src/components/activities/PastActivities.vue')['default']
    PhotosActivities: typeof import('./src/components/activities/PhotosActivities.vue')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/ui/Search.vue')['default']
    SearchToggle: typeof import('./src/components/ui/SearchToggle.vue')['default']
    SectionCard: typeof import('./src/components/ui/SectionCard.vue')['default']
    TextCard: typeof import('./src/components/ui/TextCard.vue')['default']
    ThemeSwitcher: typeof import('./src/components/ui/ThemeSwitcher.vue')['default']
    UpcomingActivities: typeof import('./src/components/activities/UpcomingActivities.vue')['default']
    UpcomingActivitiesCards: typeof import('./src/components/activities/UpcomingActivitiesCards.vue')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
