query LatestActivities($limit: Int, $offset: Int, $startDate: DateTime) {
  activities(limit: $limit, offset: $offset, end_Lt: $startDate, ordering: "begin,desc") {
    results {
      id
      description
      summary
      begin
      imageIcon
      activityLabel {
        nameNl
        nameEn
        color
        active
      }
      photos {
        thumbMedium
      }
    }
    totalCount
  }
}

query OverviewActivities($limit: Int, $offset: Int, $startDate: DateTime!) {
  activities(limit: $limit, offset: $offset, begin_Gt: $startDate, ordering: "begin,asc") {
    results {
      id
      begin
      summary
      description
      activityLabel {
        nameNl
        nameEn
        color
        active
      }
    }
    totalCount
  }
}

query PastActivities($limit: Int, $offset: Int, $endDate: DateTime) {
  activities(limit: $limit, offset: $offset, ordering: "begin,desc", begin_Lt: $endDate) {
    totalCount
    results {
      id
      begin
      description
      summary
      photos {
        caption
      }
    }
  }
}

query PhotosActivities($id: ID) {
  activity(id: $id) {
    summary
    begin
    id
    description
    photos {
      thumbMedium
      thumbMediumHeight
      thumbMediumWidth
      thumbLarge
    }
  }
}

query UpcomingActivities($limit: Int, $offset: Int, $beginDate: DateTime) {
  activities(limit: $limit, offset: $offset, begin_Gt: $beginDate, ordering: "begin,asc") {
    results {
      id
      begin
      description
      summary
      imageIcon
      activityLabel {
        nameNl
        nameEn
        color
        active
      }
    }
    totalCount
  }
}

query DemoOverviewActivities($limit: Int, $offset: Int, $beginDate: DateTime) {
  activities(limit: $limit, offset: $offset, begin_Gt: $beginDate, ordering: "begin,desc") {
    results {
      id
      begin
      description
      summary
      description
      activityLabel {
        nameNl
        nameEn
        color
        active
      }
    }
    totalCount
  }
}

query ActivitiesSliderCard($endgt: DateTime, $limit: Int) {
  activities(end_Gt: $endgt, limit: $limit) {
    results {
      photos {
        thumbMedium
      }
    }
  }
}

query HomepageSlider($limit: Int, $beginDate: DateTime) {
  activities(limit: $limit, begin_Lt: $beginDate, ordering: "begin,desc") {
    results {
      id
      description
      summary
      begin
      photos {
        thumbLarge
      }
    }
    totalCount
  }
}

query LatestNews($limit: Int) {
  newsItems(limit: $limit) {
    results {
      id
      title
      introduction
      introduction
      publicationDate
    }
    totalCount
  }
}

query OverviewNews($limit: Int, $offset: Int) {
  newsItems(limit: $limit, offset: $offset) {
    results {
      id
      title
      introduction
      publicationDate
    }
    totalCount
  }
}

query SingleActivities($id: ID) {
  activity(id: $id) {
    begin
    id
    summary
    description
    photos {
      thumbMedium
      thumbMediumHeight
      thumbMediumWidth
    }
    location
    hasCosts
    price
    activityLabel {
      nameEn
      explanationEn
    }
    organizer {
      name
    }
    enrollmentEnd
    enrollmentBegin
  }
}

query SingleNews($id: ID) {
  newsItem(id: $id) {
    content
    title
    publicationDate
    author
    id
  }
}

query EducationView {
  educationpages {
    results {
      id
      slug
      name
      content
    }
  }
}

query PageView($pageId: ID) {
  page(id: $pageId) {
    name
    slug
    content
  }
}

query PublicationOverview($limit: Int, $offset: Int) {
  publications(limit: $limit, offset: $offset, ordering: "datePublished,desc") {
    results {
      id
      name
      description
      datePublished
      publicationType {
        typeName
        description
      }
      thumbnail
      file
      isFeatured
      public
    }
    totalCount
  }
}

query CommitteeOverview {
  committees(includeAbolished: false, limit: 500) {
    results {
      name
      slug
      id
      category {
        name
      }
    }
  }
}

query SingleCommittee($committeeId: ID) {
  committees(includeAbolished: false, id: $committeeId) {
    results {
      name
      slug
      id
      email
      founded
      website
      information
      groupPicture
      logo
      abolished
      category {
        name
      }
      functionSet {
        person
        function
      }
    }
  }
}

mutation SetLanguageMutation($languageCode: String!) {
  setLanguage(languageCode: $languageCode) {
    language
    result
  }
}
